name: CI/CD

on:
  push:
    branches: [ main ]
    paths-ignore:
    - '.gitignore'
    - '.dockerignore'

jobs:
  Continuous_Integration:   #job 이름
    runs-on: ubuntu-latest  #job을 실행할 환경
    steps:

    - uses: actions/checkout@v4 # uses=액션들. 이미 만들어진 액션을 검색해서 가져다 쓰면된다. 해당 레포에 접근 권한이 있다면 레포를 가져올것.
      with:
        fetch-depth: 1          #가장 최근 commit한 히스토리만 가져온다.

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # 3. Docker 로그인 (Docker Hub, ECR 등)
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  # Docker Hub 로그인 사용자명
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set Variables
      id: set-var
      run: |
        echo "DOCKER_REGISTRY=oolralra" >> $GITHUB_ENV
        echo "DOCKER_REPOSITORY1=back" >> $GITHUB_ENV #본인 ecr레포에 맞게 수정
        echo "DOCKER_REPOSITORY2=front" >> $GITHUB_ENV #본인 ecr레포에 맞게 수정
        echo "IMAGE_TAG=${{ github.run_number }}" >> $GITHUB_ENV
        echo "GIT_EMAIL=oolralra@gmail.com" >> $GITHUB_ENV
        echo "GIT_NAME=oolralra" >> $GITHUB_ENV
   
    - name: Docker Image Build
      id: build-image
      run: |
        docker build -t ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_REPOSITORY1 }}:${{ env.IMAGE_TAG }} .

    - name: Docker image Push
      id: push-image
      run: |
        docker push ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_REPOSITORY1 }}:${{ env.IMAGE_TAG }}

    - name: Checkout Deployment Repository
      uses: actions/checkout@v4
      with:
        repository: oolralra/my_deploy #본인에 맞게 수정
        ref: main  # branch
        token: ${{ secrets.GH_TOKEN }}
        
    - name: k8s manifest update
      run: |
        sed -i "s@ \
        image: ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_REPOSITORY1 }}:.*@ \
        image: ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_REPOSITORY1 }}:${{ env.IMAGE_TAG }}@g" back.yml

    - name: Commit and Push
      run: |
        git config user.email ${{ env.GIT_EMAIL }}
        git config user.name ${{ env.GIT_NAME }}
        git add back.yml
        git commit -m "Update image tag"
        git push origin main
